<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostoGraduacoesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('posto_graduacoes')->insert([
            [
                'id' => '1',
                'instituicao_id' => '1',
                'nome' => 'Marechal',
                'sigla' => 'Mar',
                "img" => null,
                'ord' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '2',
                'instituicao_id' => '1',
                'nome' => 'General de Exercito',
                'sigla' => 'GEN EXE',
                "img" => null,
                'ord' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '3',
                'instituicao_id' => '1',
                'nome' => 'General de Divisão',
                'sigla' => 'GEN DIV',
                "img" => null,
                'ord' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '4',
                'instituicao_id' => '1',
                'nome' => 'General de Brigada',
                'sigla' => 'GEN BDA',
                "img" => null,
                'ord' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '5',
                'instituicao_id' => '1',
                'nome' => 'CORONEL',
                'sigla' => 'CEL',
                "img" => null,
                'ord' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '6',
                'instituicao_id' => '1',
                'nome' => 'Tenente Coronel',
                'sigla' => 'TC',
                "img" => null,
                'ord' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '7',
                'instituicao_id' => '1',
                'nome' => 'Major',
                'sigla' => 'MAJ',
                "img" => null,
                'ord' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '8',
                'instituicao_id' => '1',
                'nome' => 'Capitão',
                'sigla' => 'CAP',
                "img" => null,
                'ord' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '9',
                'instituicao_id' => '1',
                'nome' => '1° Tenente',
                'sigla' => '1° TEN',
                "img" => null,
                'ord' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '10',
                'instituicao_id' => '1',
                'nome' => '2° Tenente',
                'sigla' => '2° TEN',
                "img" => null,
                'ord' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '11',
                'instituicao_id' => '1',
                'nome' => 'Aspirante',
                'sigla' => 'Asp',
                "img" => null,
                'ord' => 11,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '12',
                'instituicao_id' => '1',
                'nome' => 'Sub Tenente',
                'sigla' => 'ST',
                "img" => null,
                'ord' => 12,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '13',
                'instituicao_id' => '1',
                'nome' => '1° Sargento',
                'sigla' => '1° SGT',
                "img" => null,
                'ord' => 13,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '14',
                'instituicao_id' => '1',
                'nome' => '2° Sargento',
                'sigla' => '2° SGT',
                "img" => null,
                'ord' => 14,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '15',
                'instituicao_id' => '1',
                'nome' => '3° Sargento',
                'sigla' => '3° SGT',
                "img" => null,
                'ord' => 15,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '16',
                'instituicao_id' => '1',
                'nome' => 'Cabo',
                'sigla' => 'CB',
                "img" => null,
                'ord' => 16,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '17',
                'instituicao_id' => '1',
                'nome' => 'Soldado Efv Prf',
                'sigla' => 'SD EP',
                "img" => null,
                'ord' => 17,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '18',
                'instituicao_id' => '1',
                'nome' => 'Soldado Efv Vrv',
                'sigla' => 'SD EV',
                "img" => null,
                'ord' => 18,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]
            ]);
    }
}
